### PR TITLE
add throughput data of SpS in ETC

### PR DESCRIPTION
**Pull request by kiyoyabe**
filename convention:
	* _blu means blue arm
	* _red means red arm
	* _nir means NIR arm
	* _mid means midium resolution arm
	* _opt means optics transmission
	* _dic means dichroic transmission
	* _vph means VPH transmission

file contains the followings:
	* wavelength in nm
	* transmission

Please populate them into appropriate locations

### CODE REVIEW

**Review by PaulPrice — CHANGES_REQUESTED** [review]
Could you please add a `README.txt` that details the provenance of the data?
Also, it's important to be clear what you mean by "transmission of the instrument". What elements does each file include?
* Atmosphere
* Telescope
* Corrector
* Fibers
* Spectrograph
* Detectors

**Comment by CraigLoomis** [comment]
Ditto on recording the provenance.

**Comment by kiyoyabe** [comment]
OK. Now I found we probably need all information other than dichroic. Do we need atmospheric transmission?

**Comment by PaulPrice** [comment]
Yes, please.

**Comment by kiyoyabe** [comment]
Maybe I don't understand the pull request process, but I have already pushed the revision.

**Comment by PaulPrice** [comment]
Looks great, thanks. I suggest we squash the two commits and merge. I can do that if you would like; just let me know.

**Review by PaulPrice — APPROVED** [review]

**Comment by kiyoyabe** [comment]
Could you do that, please?

**Pull request merged**
